# Generated by Django 3.2.13 on 2022-05-13 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
    ]
